<template>
  <div class="f-wh100 y-t-c " :class="loading?'slit-out-horizontal':''">
    <div class="form">
      <div class="form-bg"></div>
      <div class="form-data">
        <a-page-header
          title="Login"
          :backIcon="false"
          sub-title="This is a licensed application"
          @back="() => null"
        />
        <a-form
          layout="vertical"
          :model="formState"
          name="basic"
          :label-col="{ span: 8 }"
          :wrapper-col="{ span: 24 }"
          autocomplete="off"
          @finish="onFinish"
          @finishFailed="onFinishFailed"
        >
          <a-form-item label="秘钥" name="key" :rules="[{ required: true, message: '请输入启动秘钥!' }]">
            <a-input v-model:value="formState.key" allowClear placeholder="启动秘钥" :disabled="loading" @change="inputChange" />
          </a-form-item>

          <a-form-item label="商品名" name="name" :rules="[{ required: false, message: '请输入商品名称!' }]">
            <a-input v-model:value="formState.name" allowClear placeholder="商品名(可选)" :disabled="loading" @change="inputChange" />
          </a-form-item>
          <a-form-item label="类型" name="type" :rules="[{ required: false, message: '请输入类型!' }]">
            <a-input v-model:value="formState.type" allowClear placeholder="类型(可选)" :disabled="loading" @change="inputChange" />
          </a-form-item>
          <a-form-item :wrapper-col="{ offset: 18, span: 6 }">
            <a-button type="primary" html-type="submit" :loading="loading">启动</a-button>
          </a-form-item>
        </a-form>
      </div>

    </div>
  </div>
</template>
<script setup lang="ts">
import { ClientJS } from 'clientjs'
const emit = defineEmits(['change'])
// const props = defineProps({
//   formState:{
//     required:true,
//     type:Object
//   }
// })
interface FormState {
  key: string //工作室唯一秘钥
  name: string //商品名
  pc_id: string //设备唯一识别码
  type: string //商品类型
}
//
const formState = reactive<FormState>({
  key: 'z9b8t6szpr3w',
  name: '',
  pc_id: '',
  type: '1'
})
const loading = ref(false)
const inputChange = () => {
  nextTick(() => {
    let obj = {}
    for (const Key in formState) {
      obj[Key] = formState[Key]
    }
    localStorage.setItem('FormStateData', JSON.stringify(obj))
  })
}
// 加载指纹的方法
const loadFingerprint =async () => {

  // formState.pc_id = '4101513974'
  // console.log('生成的指纹:', fp)
  // console.log('exists',await electron.exists('C:\\Program Files\\uuidSign'))
  if(await electron.exists('C:\\Program Files\\uuidSign')){
    formState.pc_id = await electron.readFile('C:\\Program Files\\uuidSign')
    // console.log('从硬盘获取', formState.pc_id)
  }else{
    // 创建 ClientJS 实例
    const client = new ClientJS()
    // 生成指纹
    const fp = client.getFingerprint() // 获取指纹
    formState.pc_id = JSON.stringify(fp)
    await electron.createFile({
      savePath: 'C:\\Program Files\\',
      fileName: 'uuidSign',
      content: formState.pc_id,
      ensureDir: true
    })
    // console.log('写入硬盘')
  }
}
onMounted(async () => {
  // localStorage.setItem('FormStateData', '{"code":0}')
  const get: any = localStorage.getItem('FormStateData')
  if (get) {
    const jsonGet = JSON.parse(get)
    for (const sKey in formState) {
      formState[sKey] = jsonGet[sKey]
    }
  }
})

onMounted(() => {
  loadFingerprint()
})

const onFinish = async (_values: any) => {
  // console.log('Success:', values);
  loading.value = true
  const newData = {
    ...formState
  }
  emit('change', newData)
}

const onFinishFailed = async (_errorInfo: any) => {}
</script>
<style scoped lang="scss">
.form {
  width: 350px;
  height: 410px;
  //padding: 30px;
  margin-top: 50px;
  position: relative;
  z-index: 1000;
  &-data{
    padding: 15px;
    width: 100%;
    height: 100%;
    position: relative;
  }
  &-bg {
    width: 100%;
    height: 100%;
    background-color: #ffffff;
    position: absolute;
    border-radius: 30px;
    opacity: 0.5;
  }
}
.slit-out-horizontal {
  animation: slit-out-horizontal 0.5s ease-in both;
}
/* ----------------------------------------------
 * Generated by Animista on 2025-4-2 1:10:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slit-out-horizontal
 * ----------------------------------------
 */
@keyframes slit-out-horizontal {
  0% {
    transform: translateZ(0) rotateX(0);
    opacity: 1;
  }
  54% {
    transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
}

</style>
